### PR TITLE
ENH: Update extension metadata

### PR DESCRIPTION
**Pull request by jcfr**
Consolidate extension metadata based on the corresponding s4ext file organized
in the ExtensionsIndex repository.

### CODE REVIEW

**Comment by jcfr** [comment]
@e-simpson It would be great if this could be reviewed & integrated :pray: 

cc: @lassoan @pieper

**Comment by jcfr** [comment]
Please, could this be reviewed & merged :pray:

**Comment by jcfr** [comment]
Email sent on June 13th 2024 to @e-simpson with @lassoan and @pieper in cc:

```
Subject: Help to merge https://github.com/Auditory-Biophysics-Lab/Slicer-BoneThicknessMapping/pull/7

Hi Evan,

When you have a chance, we would appreciate your help to merge the following pull request:

  ENH: Update extension metadata
  https://github.com/Auditory-Biophysics-Lab/Slicer-BoneThicknessMapping/pull/7

Changes are trivial as they only include updates to the extension metadata.

Thanks
J-Christophe
```

**Comment by jcfr** [comment]
@e-simpson   Thanks for taking the time to follow-up :pray: :rocket:

**Comment by e-simpson** [comment]
> @e-simpson Thanks for taking the time to follow-up 🙏 🚀

No problem. Apologies for the delay in getting to this. Thanks for sticking on top of it.

**Pull request merged**
